openapi: 3.0.1
info:
  title: HERO
  version: "1.0.0"
paths:
  /provider/upload/validation:
    post:
      summary: Endpoint to upload validation JSON payloads.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadPayload'
      responses:
        '200':
          description: The JSON was uploaded successfully.
        '500':
          description: A problem when processing the json upload request occured.
      tags:
        - Upload

  /provider/upload/approval:
    post:
      summary: Endpoint to upload approval JSON payloads.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadPayload'
      responses:
        '200':
          description: The JSON was uploaded successfully.
        '500':
          description: A problem when processing the json upload request occured.
      tags:
        - Upload

components:
  schemas:
    UploadPayload:
      type: object
      properties:
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        id:
          type: string
        title:
          type: string
        description:
          type: string
        isAdoptedBy:
          type: string
        machineDepartment:
          type: string
        machineManufacturer:
          type: string
        machineName:
          type: string
        machineSite:
          type: string
        machineType:
          type: string
        status:
          type: string
        type:
          type: string
        user:
          type: string
        hasStep:
          type: array
          items:
            $ref: '#/components/schemas/Step'
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'

    Step:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        energyPoint:
          $ref: '#/components/schemas/EnergyPoint'
        hasStep:
          type: array
          items:
            $ref: '#/components/schemas/Step'
        hasStepVerification:
          type: array
          items:
            $ref: '#/components/schemas/StepVerification'
        isOptional:
          type: boolean
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
        substepsPolicy:
          type: string

    EnergyPoint:
      type: object
      properties:
        energyPointIdentifier:
          type: string
        energySource:
          type: string
        isEnergyPoint:
          type: boolean
        ppe:
          type: array
          items:
            type: string
        typeOfLock:
          type: array
          items:
            type: string

    StepVerification:
      type: object
      properties:
        title:
          type: string
        description:
          type: string

    Reference:
      type: object
      properties:
        format:
          type: string
        resource:
          type: object
          properties:
            key:
              type: string
            url:
              type: string
              format: uri
        title:
          type: string

tags:
  - name: Upload
    description: Endpoints for uploading Validation and Approval JSON payloads.
