openapi: 3.0.1
info:
  title: Beko
  version: "1.0.0"
paths:
  /v1/Beko/PkmsService:
    post:
      tags:
        - dynamic
      summary: Pkms Service endpoint
      requestBody:
        description: Payload for PkmsService
        content:
          application/json:
            schema:
              type: object
              properties:
                uuid:
                  type: string
                trace_id:
                  type: string
                procedure_id:
                  type: string
                  format: uri
                action:
                  type: string
                timestamp:
                  type: string
                  format: date-time
      responses:
        "200":
          description: Ok
  /v1/Beko/ProcedureExtractionService:
    post:
      tags:
        - dynamic
      summary: Procedure Extraction Service endpoint
      requestBody:
        description: Payload for ProcedureExtractionService
        content:
          application/json:
            schema:
              type: object
              properties:
                static:
                  type: object
                  properties:
                    ruleset_name:
                      type: string
                    version:
                      type: string
                    description:
                      type: string
                    formalism:
                      type: string
                    scope:
                      type: string
                    input_conditions:
                      type: string
                    validation_metrics:
                      type: string
                    validation_results:
                      type: string
                    risks:
                      type: string
                    biases:
                      type: string
                    deployment_information:
                      type: string
                    license:
                      type: string
                    contact_information:
                      type: string
                    source_code:
                      type: string
                dynamic:
                  type: object
                  properties:
                    start_timestamp:
                      type: string
                      format: date-time
                    end_timestamp:
                      type: string
                      format: date-time
                    error_id:
                      type: array
                      items:
                        type: string
                    status:
                      type: number
                    input_id:
                      type: string
                    output_id:
                      type: string
                    hash:
                      type: string
                    document_id:
                      type: string
                    model_version:
                      type: string
                    output_hash:
                      type: string
                errors:
                  type: array
                  items:
                    type: string
                uuid:
                  type: string
      responses:
        "200":
          description: Ok
  /v1/Beko/ProcedureManualExtractionService:
    post:
      tags:
        - dynamic
      summary: Procedure Manual Extraction Service endpoint
      requestBody:
        description: Payload for ProcedureManualExtractionService
        content:
          application/json:
            schema:
              type: object
              properties:
                intermediate_format:
                  type: object
                  properties:
                    type:
                      type: string
                    created:
                      type: string
                      format: date-time
                    modified:
                      type: string
                      format: date-time
                    title:
                      type: string
                    status:
                      type: string
                    user:
                      type: string
                    machine_type:
                      type: string
                    machine_manufacturer:
                      type: string
                    machine_department:
                      type: string
                    machine_name:
                      type: string
                    machine_site:
                      type: string
                hash:
                  type: string
                diff:
                  type: object
                trace_id:
                  type: string
                action:
                  type: string
                timestamp:
                  type: string
                  format: date-time
                uuid:
                  type: string
      responses:
        "200":
          description: Ok
  /v1/Beko/ProcedureApprovalService:
    post:
      tags:
        - dynamic
      summary: Procedure Approval Service endpoint
      requestBody:
        description: Payload for ProcedureApprovalService
        content:
          application/json:
            schema:
              type: object
              properties:
                intermediate_format:
                  type: object
                  properties:
                    machine_type:
                      type: string
                    machine_manufacturer:
                      type: string
                    created:
                      type: string
                      format: date-time
                    machine_department:
                      type: string
                    modified:
                      type: string
                      format: date-time
                    machine_name:
                      type: string
                    title:
                      type: string
                    type:
                      type: string
                    hash:
                      type: string
                    machine_site:
                      type: string
                    status:
                      type: string
                    user:
                      type: string
                uuid:
                  type: string
                validation:
                  type: object
                  properties:
                    end_timestamp:
                      type: string
                      format: date-time
                    validation_id:
                      type: string
                approval:
                  type: object
                  properties:
                    start_timestamp:
                      type: string
                      format: date-time
                    approval_id:
                      type: string
                confirmation:
                  type: object
                  properties:
                    end_timestamp:
                      type: string
                      format: date-time
                    confirmation_id:
                      type: string
                    status:
                      type: string
                    comment:
                      type: string
      responses:
        "200":
          description: Ok
  /v1/Beko/ProcedureConfirmationService:
    post:
      tags:
        - dynamic
      summary: Procedure Confirmation Service endpoint
      requestBody:
        description: Payload for ProcedureConfirmationService
        content:
          application/json:
            schema:
              type: object
              properties:
                intermediate_format:
                  type: object
                  properties:
                    machine_type:
                      type: string
                    machine_manufacturer:
                      type: string
                    created:
                      type: string
                      format: date-time
                    machine_department:
                      type: string
                    modified:
                      type: string
                      format: date-time
                    machine_name:
                      type: string
                    title:
                      type: string
                    type:
                      type: string
                    hash:
                      type: string
                    machine_site:
                      type: string
                    status:
                      type: string
                    user:
                      type: string
                uuid:
                  type: string
                approval:
                  type: object
                  properties:
                    end_timestamp:
                      type: string
                      format: date-time
                    approval_id:
                      type: string
                confirmation:
                  type: object
                  properties:
                    start_timestamp:
                      type: string
                      format: date-time
                    confirmation_id:
                      type: string
      responses:
        "200":
          description: Ok
  /v1/Beko/ProcedureConfirmedService:
    post:
      tags:
        - dynamic
      summary: Procedure Confirmed Service endpoint
      requestBody:
        description: Payload for ProcedureConfirmedService
        content:
          application/json:
            schema:
              type: object
              properties:
                intermediate_format:
                  type: object
                  properties:
                    machine_type:
                      type: string
                    machine_manufacturer:
                      type: string
                    created:
                      type: string
                      format: date-time
                    machine_department:
                      type: string
                    modified:
                      type: string
                      format: date-time
                    machine_name:
                      type: string
                    title:
                      type: string
                    type:
                      type: string
                    hash:
                      type: string
                    machine_site:
                      type: string
                    status:
                      type: string
                    user:
                      type: string
                uuid:
                  type: string
                confirmation:
                  type: object
                  properties:
                    end_timestamp:
                      type: string
                      format: date-time
                    confirmation_id:
                      type: string
                    status:
                      type: string
      responses:
        "200":
          description: Ok
  /v1/Beko/ProcedureValidationService:
    post:
      tags:
        - dynamic
      summary: Procedure Validation Service endpoint
      requestBody:
        description: Payload for ProcedureValidationService
        content:
          application/json:
            schema:
              type: object
              properties:
                intermediate_format:
                  type: object
                  properties:
                    machine_type:
                      type: string
                    machine_manufacturer:
                      type: string
                    created:
                      type: string
                      format: date-time
                    machine_department:
                      type: string
                    modified:
                      type: string
                      format: date-time
                    machine_name:
                      type: string
                    title:
                      type: string
                    type:
                      type: string
                    hash:
                      type: string
                    machine_site:
                      type: string
                    status:
                      type: string
                    user:
                      type: string
                uuid:
                  type: string
                validation:
                  type: object
                  properties:
                    start_timestamp:
                      type: string
                      format: date-time
                    validation_id:
                      type: string
                confirmation:
                  type: object
                  properties:
                    end_timestamp:
                      type: string
                      format: date-time
                    confirmation_id:
                      type: string
                    status:
                      type: string
                    comment:
                      type: string
      responses:
        "200":
          description: Ok